/*
 * Copyright 2004-2015 the Seasar Foundation and the Others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.seasar.extension.jdbc.util;

import java.io.PrintWriter;
import java.sql.*;
import java.util.Map;
import java.util.Set;
import java.util.logging.Logger;

import javax.sql.DataSource;

import org.seasar.extension.unit.S2TestCase;
import org.seasar.framework.util.DriverManagerUtil;

/**
 * @author higa
 * 
 */
public class DatabaseMetaDataUtilTest extends S2TestCase {

    /**
     * @throws Exception
     */
    public void testGetColumnList() throws Exception {
        DatabaseMetaData dbMetaData = getDatabaseMetaData();
        Map columnMap = DatabaseMetaDataUtil.getColumnMap(dbMetaData, "emp");
        System.out.println(columnMap);
        assertTrue("1", columnMap.size() > 0);
    }

    /**
     * @throws Exception
     */
    public void testSpike() throws Exception {
        DatabaseMetaData dbMetaData = getDatabaseMetaData();
        System.out.println(dbMetaData.getDatabaseProductName());
        System.out.println(dbMetaData.getDatabaseProductVersion());
    }

    /**
     * @throws Exception
     */
    public void testGetColumnListForNotExistTable() throws Exception {
        DatabaseMetaData dbMetaData = getDatabaseMetaData();
        Map columnMap = DatabaseMetaDataUtil.getColumnMap(dbMetaData, "_emp_");
        assertEquals("1", 0, columnMap.size());
    }

    /**
     * @throws Exception
     */
    public void testGetColumnListForSchema() throws Exception {
        DatabaseMetaData dbMetaData = getDatabaseMetaData();
        Map columnMap = DatabaseMetaDataUtil.getColumnMap(dbMetaData, "SA.emp");
        System.out.println(columnMap);
        assertTrue("1", columnMap.size() > 0);
    }

    /**
     * @throws Exception
     */
    public void testGetPrimaryKeyList() throws Exception {
        DatabaseMetaData dbMetaData = getDatabaseMetaData();
        Set primaryKeySet = DatabaseMetaDataUtil.getPrimaryKeySet(dbMetaData,
                "emp");
        System.out.println(primaryKeySet);
        assertTrue("1", primaryKeySet.size() > 0);
        System.out.println(dbMetaData.getDatabaseProductName());
    }

    /**
     * @throws Exception
     */
    public void testSupportsGetGeneratedKeys() throws Exception {
        DatabaseMetaData dbMetaData = getDatabaseMetaData();
        assertFalse(DatabaseMetaDataUtil.supportsGetGeneratedKeys(dbMetaData));
    }

    public void setUp() {
        include("DatabaseMetaDataUtilTest.dicon");
    }

    /**
     *
     */
    public static class SimpleDataSource implements DataSource {

        private String driverClassName_;

        private String url_;

        private String user_;

        private String password_;

        public Connection getConnection() throws SQLException {
            DriverManagerUtil.registerDriver(driverClassName_);
            return DriverManager.getConnection(url_, user_, password_);
        }

        public Connection getConnection(String username, String password)
                throws SQLException {
            return null;
        }

        public PrintWriter getLogWriter() throws SQLException {
            return null;
        }

        public void setLogWriter(PrintWriter out) throws SQLException {
        }

        public void setLoginTimeout(int seconds) throws SQLException {
        }

        public int getLoginTimeout() throws SQLException {
            return 0;
        }

        /**
         * Return the parent Logger of all the Loggers used by this data source. This
         * should be the Logger farthest from the root Logger that is
         * still an ancestor of all of the Loggers used by this data source. Configuring
         * this Logger will affect all of the log messages generated by the data source.
         * In the worst case, this may be the root Logger.
         *
         * @return the parent Logger for this data source
         * @throws SQLFeatureNotSupportedException if the data source does not use
         *                                         {@code java.util.logging}
         * @since 1.7
         */
        @Override
        public Logger getParentLogger() throws SQLFeatureNotSupportedException {
            return null;
        }

        /**
         * @param driverClassName
         */
        public void setDriverClassName(String driverClassName) {
            driverClassName_ = driverClassName;
        }

        /**
         * @param password
         */
        public void setPassword(String password) {
            password_ = password;
        }

        /**
         * @param url
         */
        public void setURL(String url) {
            url_ = url;
        }

        /**
         * @param user
         */
        public void setUser(String user) {
            user_ = user;
        }

        /**
         * Returns an object that implements the given interface to allow access to
         * non-standard methods, or standard methods not exposed by the proxy.
         * <p>
         * If the receiver implements the interface then the result is the receiver
         * or a proxy for the receiver. If the receiver is a wrapper
         * and the wrapped object implements the interface then the result is the
         * wrapped object or a proxy for the wrapped object. Otherwise return the
         * the result of calling <code>unwrap</code> recursively on the wrapped object
         * or a proxy for that result. If the receiver is not a
         * wrapper and does not implement the interface, then an <code>SQLException</code> is thrown.
         *
         * @param iface A Class defining an interface that the result must implement.
         * @return an object that implements the interface. May be a proxy for the actual implementing object.
         * @throws SQLException If no object found that implements the interface
         * @since 1.6
         */
        @Override
        public <T> T unwrap(Class<T> iface) throws SQLException {
            return null;
        }

        /**
         * Returns true if this either implements the interface argument or is directly or indirectly a wrapper
         * for an object that does. Returns false otherwise. If this implements the interface then return true,
         * else if this is a wrapper then return the result of recursively calling <code>isWrapperFor</code> on the wrapped
         * object. If this does not implement the interface and is not a wrapper, return false.
         * This method should be implemented as a low-cost operation compared to <code>unwrap</code> so that
         * callers can use this method to avoid expensive <code>unwrap</code> calls that may fail. If this method
         * returns true then calling <code>unwrap</code> with the same argument should succeed.
         *
         * @param iface a Class defining an interface.
         * @return true if this implements the interface or directly or indirectly wraps an object that does.
         * @throws SQLException if an error occurs while determining whether this is a wrapper
         *                      for an object with the given interface.
         * @since 1.6
         */
        @Override
        public boolean isWrapperFor(Class<?> iface) throws SQLException {
            return false;
        }
    }

}